import { brand, APP_URL } from "@/lib/brand"
import { PLANS, toNpr } from "@/lib/pricing"

export const SITE_URL = "https://www.awwtomation.com"
export const SITE_NAME = brand.name
/** Generated by app/opengraph-image.tsx. Set explicitly because a page-level openGraph object replaces the inherited one. */
export const OG_IMAGE = { url: "/opengraph-image", width: 1200, height: 630, alt: "Awwtomation · Instagram DMs on autopilot" }

export interface BreadcrumbItem {
  name: string
  href: string
}

export interface FaqItem {
  question: string
  answer: string
}

export function absoluteUrl(path: string) {
  if (path.startsWith("http")) return path
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`
}

/* ------------------------------------------------------------------ *
 * Page metadata
 * ------------------------------------------------------------------ */

export interface PageSeo {
  title: string
  description: string
  path: string
}

/**
 * Build a Next `Metadata` object with canonical, OG and Twitter tags filled
 * in. Every page goes through here so no page can ship without a canonical.
 */
export function pageMetadata({ title, description, path }: PageSeo) {
  const url = absoluteUrl(path)
  // The layout's title template adds the brand to <title>; social cards do not
  // get that template, so they carry it explicitly.
  const socialTitle = title.includes(SITE_NAME) ? title : `${title} · ${SITE_NAME}`
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title: socialTitle,
      description,
      url,
      siteName: SITE_NAME,
      type: "website" as const,
      locale: "en_NP",
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image" as const,
      title: socialTitle,
      description,
      images: [OG_IMAGE.url],
    },
  }
}

/* ------------------------------------------------------------------ *
 * Structured data
 * ------------------------------------------------------------------ */

export function buildOrganizationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": `${SITE_URL}/#organization`,
    name: brand.name,
    url: SITE_URL,
    logo: absoluteUrl("/full-logo.svg"),
    description: brand.description,
    email: brand.supportEmail,
    address: {
      "@type": "PostalAddress",
      addressLocality: brand.city,
      addressCountry: "NP",
    },
    areaServed: {
      "@type": "Country",
      name: "Nepal",
    },
    contactPoint: {
      "@type": "ContactPoint",
      contactType: "customer support",
      email: brand.supportEmail,
      areaServed: "NP",
      availableLanguage: ["English", "Nepali"],
    },
  }
}

export function buildWebsiteSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${SITE_URL}/#website`,
    url: SITE_URL,
    name: SITE_NAME,
    description: brand.description,
    publisher: { "@id": `${SITE_URL}/#organization` },
    inLanguage: "en",
  }
}

/**
 * The product itself. Offers carry NPR because that is the price shown on the
 * pricing page; the USD amount actually charged is stated alongside it there.
 */
export function buildSoftwareSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "@id": `${SITE_URL}/#software`,
    name: brand.name,
    applicationCategory: "BusinessApplication",
    applicationSubCategory: "Marketing Automation",
    operatingSystem: "Web browser",
    url: SITE_URL,
    description: brand.description,
    publisher: { "@id": `${SITE_URL}/#organization` },
    featureList: [
      "Instagram comment to DM automation",
      "Instagram DM keyword autoresponder",
      "Instagram story reply automation",
      "Facebook Page comment automation",
      "Visual flow builder",
      "Unified Instagram and Messenger inbox",
      "Contacts, pipelines and segments",
      "Broadcasts",
      "Tracked links with click attribution",
      "Automation analytics",
    ],
    offers: PLANS.map((plan) => ({
      "@type": "Offer",
      name: plan.label,
      price: plan.priceUsd === 0 ? "0" : String(toNpr(plan.priceUsd)),
      priceCurrency: "NPR",
      category: plan.priceUsd === 0 ? "free" : "subscription",
      url: absoluteUrl("/pricing"),
      availability: "https://schema.org/InStock",
      eligibleRegion: { "@type": "Country", name: "Nepal" },
    })),
  }
}

export function buildBreadcrumbSchema(items: BreadcrumbItem[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: absoluteUrl(item.href),
    })),
  }
}

export function buildFaqSchema(faqs: FaqItem[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: { "@type": "Answer", text: faq.answer },
    })),
  }
}

export function buildWebPageSchema({ title, description, path }: PageSeo) {
  return {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "@id": `${absoluteUrl(path)}#webpage`,
    url: absoluteUrl(path),
    name: title,
    description,
    isPartOf: { "@id": `${SITE_URL}/#website` },
    about: { "@id": `${SITE_URL}/#software` },
    inLanguage: "en",
  }
}

export function buildItemListSchema({
  name,
  items,
}: {
  name: string
  items: { name: string; href: string; description?: string }[]
}) {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name,
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      description: item.description,
      url: absoluteUrl(item.href),
    })),
  }
}

/** HowTo schema for use-case pages that describe a setup sequence. */
export function buildHowToSchema({
  name,
  description,
  steps,
}: {
  name: string
  description: string
  steps: { name: string; text: string }[]
}) {
  return {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name,
    description,
    step: steps.map((step, index) => ({
      "@type": "HowToStep",
      position: index + 1,
      name: step.name,
      text: step.text,
    })),
  }
}

export const APP_SIGNUP_URL = `${APP_URL}/login`
