"use client"

import Link from "next/link"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { ExternalLink } from "lucide-react"

interface SampleOutputModalProps {
  sampleOutputUrl: string
}

export function SampleOutputModal({ sampleOutputUrl }: SampleOutputModalProps) {
  const [open, setOpen] = useState(false)

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className="w-full md:w-auto bg-transparent">
          View Sample Output
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>Sample Output</DialogTitle>
          <DialogDescription>
            Click the link below to view a sample of the output generated by this automation template.
          </DialogDescription>
        </DialogHeader>
        <div className="py-4">
          <Link
            href={sampleOutputUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 text-blue-600 hover:underline"
          >
            Open Sample PDF <ExternalLink className="h-4 w-4" />
          </Link>
        </div>
      </DialogContent>
    </Dialog>
  )
}
